package com.openassist.ui.navigation

enum class OpenAssistDestination(val title: String) {
    Splash("Splash"),
    Onboarding("Onboarding"),
    Chat("Home"),
    UniversalSearch("Universal Search"),
    CommandPalette("Command Palette"),
    AgentTaskCenter("Agent Task Center"),
    ContextSidebar("Context Sidebar"),
    ConnectionsHub("Connections"),
    CorePlatform("Core Platform"),
    Settings("Settings"),
    ModelSelection("Model Selection"),
    Permissions("Permissions"),
    ToolApproval("Tool Approval"),
    MCPServers("MCP Servers"),
    ConversationHistory("History"),
    About("About"),
    AiModeSelector("AI Mode"),
    LocalModels("Local Models"),
    ModelDownload("Download Models"),
    DownloadManager("Downloads"),
    StorageManager("Storage"),
    ScreenIntelligence("Screen Intelligence"),
    ActionConfirmation("Action Confirmation"),
    AutomationCenter("Automation Center"),
    SafetySettings("Safety Settings"),
    AssistantPermissions("Assistant Permissions"),
    VoiceOverlay("Voice Overlay"),
    VoiceStudio("Voice Studio"),
    VoiceMarketplace("Voice Marketplace"),
    VoiceDownloads("Voice Downloads"),
    VoiceSettings("Voice Settings"),
    VoicePreview("Voice Preview"),
    Workspace("Workspace"),
    ImageStudio("Image Studio"),
    CodeCanvas("Code Canvas"),
    PythonRunner("Python Runner"),
    DocumentEditor("Document Editor"),
    ProjectExplorer("Project Explorer"),
    FileViewer("File Viewer"),
    ArtifactManager("Artifact Manager"),
    ZipExportCenter("ZIP Export Center"),
    OutputConsole("Output Console"),
    McpMarketplace("MCP Marketplace"),
    McpDetails("MCP Details"),
    McpInstaller("MCP Installer"),
    McpPermissions("MCP Permissions"),
    McpActivityCenter("MCP Activity Center"),
    DesktopBridge("Desktop Bridge"),
    McpConnections("MCP Connections"),
    McpDeveloperCenter("MCP Developer Center"),
    McpSecurityDashboard("MCP Security Dashboard"),
    AgentEngine("Agent Engine"),
    KnowledgeBase("My Knowledge"),
    SupportTrustCenter("Support & Trust"),
    FeedbackCenter("Feedback Center"),
    ReportBug("Report Bug"),
    HelpCenter("Help Center"),
    AboutOpenAssist("About OpenAssist"),
    ContactSupport("Contact Support"),
    PrivacyCenter("Privacy Center"),
    PermissionsCenter("Permissions Center"),
    ConversationLibrary("Conversation Library"),
    AgentCenter("Agent Center"),
    WhatsNew("What's New"),
    SmartOnboarding("Smart Onboarding"),
    TipsRecommendations("Tips & Recommendations"),
    StorageAnalyzer("Storage Analyzer"),
}
